import type{BenchmarkMetric,ForecastModel,OptimizationRecommendation,RecommendationOutcome,TrendInsight}from'./intelligence-types';
export function forecastAccuracy(model:ForecastModel){const measured=model.points.filter(p=>p.actual!==undefined);if(!measured.length)return null;const mape=measured.reduce((n,p)=>n+Math.abs((p.actual!-p.predicted)/(p.actual||1)),0)/measured.length;return Math.max(0,Math.round((1-mape)*100));}
export function forecastTotal(model:ForecastModel){return model.points.reduce((n,p)=>n+p.predicted,0)}
export function recommendationPriority(r:OptimizationRecommendation){const expiry=r.expiresAt?Math.max(0,30-Math.ceil((new Date(r.expiresAt).getTime()-Date.now())/86400000)):0;return Math.round(r.impact*.55+r.confidence*.4+Math.min(expiry,5));}
export function outcomeLift(o:RecommendationOutcome){if(o.actual===undefined||o.baseline===0)return null;return Math.round((o.actual-o.baseline)/Math.abs(o.baseline)*1000)/10}
export function portfolioBenchmark(m:BenchmarkMetric,workspace:string){const value=m.workspaceValues[workspace];if(value===undefined)return null;return{value,variance:Math.round((value-m.portfolioMedian)*10)/10,above:value>=m.portfolioMedian}}
export function anomalySeverity(actual:number,expected:number,tolerancePercent:number){const variance=Math.abs(actual-expected)/(Math.abs(expected)||1)*100;return variance>=tolerancePercent*2?'critical':variance>=tolerancePercent?'warning':'normal'}
export function closedLoopReadiness(recommendations:OptimizationRecommendation[],outcomes:RecommendationOutcome[]){const implemented=recommendations.filter(r=>['implemented','measured'].includes(r.status));const measured=new Set(outcomes.filter(o=>o.actual!==undefined).map(o=>o.recommendationId));return{implemented:implemented.length,measured:implemented.filter(r=>measured.has(r.id)).length,ready:implemented.length>0&&implemented.every(r=>measured.has(r.id))}}
export function rankInsights(insights:TrendInsight[]){return[...insights].sort((a,b)=>b.strength-a.strength)}
