import { BadgeCheck, BookOpenCheck, CloudCog, Network, ClipboardCheck, HardDrive, Code2, Webhook, KeyRound, CreditCard, LifeBuoy, Activity, TrendingUp, AlertTriangle, ServerCog, ToggleLeft, Building2, Database, GitMerge, LayoutDashboard, ListChecks, Settings, Target, Search, Radio, Bot, Gauge, PackageCheck, Workflow, Megaphone, BarChart3, ClipboardList, Plug, ShieldCheck, ShieldAlert, LockKeyhole, Rocket, FlaskConical, UsersRound, BrainCircuit, CheckCircle2 } from 'lucide-react';
export const navigation = [
  { label: 'Overview', href: '/', icon: LayoutDashboard },
  { label: 'Implementation', href: '/implementation', icon: ListChecks },
  { label: 'Data Studio', href: '/data-studio', icon: Database },
  { label: 'Accounts', href: '/accounts', icon: Building2 },
  { label: 'Entity Resolution', href: '/entity-resolution', icon: GitMerge },
  { label: 'Research Queue', href: '/research', icon: Search },
  { label: 'Signals', href: '/signals', icon: Radio },
  { label: 'AI Review', href: '/ai-review', icon: Bot },
  { label: 'Scoring', href: '/scoring', icon: Gauge },
  { label: 'Offers', href: '/offers', icon: PackageCheck },
  { label: 'Playbooks', href: '/playbooks', icon: Workflow },
  { label: 'Campaigns', href: '/campaigns', icon: Megaphone },
  { label: 'Performance', href: '/performance', icon: BarChart3 },
  { label: 'Management', href: '/analytics', icon: LayoutDashboard },
  { label: 'Operating Review', href: '/operating-review', icon: ClipboardList },
  { label: 'Opportunities', href: '/opportunities', icon: Target },
  { label: 'Integrations', href: '/admin/integrations', icon: Plug },
  { label: 'Integration Marketplace', href: '/admin/integration-marketplace', icon: Plug },
  { label: 'Governance', href: '/admin/governance', icon: ShieldCheck },
  { label: 'Activation', href: '/admin/activation', icon: Rocket },
  { label: 'Pilot', href: '/pilot', icon: FlaskConical },
  { label: 'Rollout', href: '/rollout', icon: UsersRound, BrainCircuit },
  { label: 'Enterprise Intelligence', href: '/intelligence', icon: BrainCircuit },
  { label: 'Executive Intelligence', href: '/executive', icon: BarChart3 },
  { label: 'Templates', href: '/admin/templates', icon: PackageCheck },
  { label: 'Provisioning', href: '/admin/provisioning', icon: Rocket },
  { label: 'Portability', href: '/admin/portability', icon: Workflow },
  { label: 'Developer Platform', href: '/admin/developer', icon: Code2 },
  { label: 'Reliability', href: '/admin/reliability', icon: AlertTriangle },
  { label: 'Security', href: '/admin/security', icon: ShieldAlert },
  { label: 'Resilience', href: '/admin/resilience', icon: HardDrive },
  { label: 'Compliance', href: '/admin/compliance', icon: ClipboardCheck },
  { label: 'AI Operations', href: '/admin/ai-operations', icon: Bot },
  { label: 'Workflow Automation', href: '/admin/workflows', icon: Workflow },
  { label: 'Privacy', href: '/admin/privacy', icon: LockKeyhole },
  { label: 'Services & SLOs', href: '/admin/services', icon: ServerCog },
  { label: 'Incidents', href: '/admin/incidents', icon: AlertTriangle },
  { label: 'Feature Flags', href: '/admin/feature-flags', icon: ToggleLeft },
  { label: 'API Clients', href: '/admin/api-clients', icon: KeyRound },
  { label: 'Webhooks', href: '/admin/webhooks', icon: Webhook },
  { label: 'Commercial', href: '/admin/commercial', icon: CreditCard },
  { label: 'Subscriptions', href: '/admin/subscriptions', icon: Building2 },
  { label: 'Usage', href: '/admin/usage', icon: Activity },
  { label: 'Support', href: '/admin/support', icon: LifeBuoy },
  { label: 'Platform Administration', href: '/admin/platform-administration', icon: Network },
  { label: 'Performance Engineering', href: '/admin/performance-engineering', icon: TrendingUp },
  { label: 'Quality Engineering', href: '/admin/quality-engineering', icon: ClipboardCheck },
  { label: 'Production Operations', href: '/admin/production-operations', icon: CloudCog },
  { label: 'Release Enablement', href: '/admin/release-enablement', icon: BookOpenCheck },
  { label: 'GA Readiness', href: '/admin/ga-readiness', icon: BadgeCheck },
  { label: 'Launch Certification', href: '/admin/launch-certification', icon: CheckCircle2 },
  { label: 'Post-GA Operations', href: '/admin/post-ga-operations', icon: TrendingUp },
  { label: 'Administration', href: '/admin', icon: Settings }
];
