import type {CustomerFeedbackItem,CustomerHealthRecord,ImprovementInitiative,ProductAdoptionMetric,ValueOutcome} from './post-ga-operations-types';
export function adoptionRate(item:ProductAdoptionMetric){return item.eligibleUsers?Number((item.activeUsers/item.eligibleUsers*100).toFixed(1)):0;}
export function adoptionCoverage(items:ProductAdoptionMetric[]){if(!items.length)return 100;return Number((items.filter(x=>adoptionRate(x)>=x.targetPercent).length/items.length*100).toFixed(1));}
export function customerHealthCoverage(items:CustomerHealthRecord[]){if(!items.length)return 100;return Number((items.filter(x=>x.status==='healthy').length/items.length*100).toFixed(1));}
export function feedbackTriageCoverage(items:CustomerFeedbackItem[]){if(!items.length)return 100;return Number((items.filter(x=>x.status!=='new').length/items.length*100).toFixed(1));}
export function valueRealizationCoverage(items:ValueOutcome[]){if(!items.length)return 100;return Number((items.filter(x=>x.verified&&(x.direction==='higher'?x.current>=x.target:x.current<=x.target)).length/items.length*100).toFixed(1));}
export function initiativePriority(item:ImprovementInitiative){return Number((item.impactScore/Math.max(item.effortScore,1)).toFixed(2));}
export function approvedImprovementCoverage(items:ImprovementInitiative[]){if(!items.length)return 100;return Number((items.filter(x=>x.status==='approved'||x.status==='in_progress'||x.status==='completed').length/items.length*100).toFixed(1));}
export function continuousImprovementScore(adoption:ProductAdoptionMetric[],health:CustomerHealthRecord[],feedback:CustomerFeedbackItem[],outcomes:ValueOutcome[],initiatives:ImprovementInitiative[]){return Number(((adoptionCoverage(adoption)+customerHealthCoverage(health)+feedbackTriageCoverage(feedback)+valueRealizationCoverage(outcomes)+approvedImprovementCoverage(initiatives))/5).toFixed(1));}
export function readyForNextRelease(adoption:ProductAdoptionMetric[],health:CustomerHealthRecord[],feedback:CustomerFeedbackItem[],outcomes:ValueOutcome[],initiatives:ImprovementInitiative[]){return continuousImprovementScore(adoption,health,feedback,outcomes,initiatives)>=80&&feedback.every(x=>x.impact!=='critical'||x.status==='resolved'||x.status==='planned')&&initiatives.some(x=>x.targetRelease==='1.1.0'&&(x.status==='approved'||x.status==='in_progress'));}
