import Link from 'next/link';import {notFound} from 'next/navigation';import {getWorkspaceContext} from '@/lib/workspace-context';import {getAccountDetail} from '@/lib/data/entities';import {getAccountBrief} from '@/lib/data/research';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default async function Page({params}:{params:Promise<{accountId:string}>}){const {accountId}=await params;const {activeWorkspace}=await getWorkspaceContext();const a=await getAccountDetail(activeWorkspace!.id,accountId);if(!a)notFound();const brief=await getAccountBrief(activeWorkspace!.id,accountId);return <>
<Link className="text-link" href="/accounts">← Accounts</Link><div className="hero section"><div><div className="eyebrow">{a.lifecycle} · Priority {a.priority}</div><h1>{a.name}</h1><p className="muted">{a.industry} · {a.city}, {a.state}</p></div><div className="action-row"><button className="secondary-btn">Request research</button><button className="secondary-btn">Create task</button><button className="btn button-reset">Create opportunity</button></div></div>
<div className="grid cards section"><div className="card"><span className="muted">Account score</span><div className="metric">{a.score}</div><small>{a.dataConfidence}% data confidence</small></div><div className="card"><span className="muted">Opportunity value</span><div className="metric">{money.format(a.opportunityValue)}</div></div><div className="card"><span className="muted">Properties</span><div className="metric">{a.properties.length}</div></div><div className="card"><span className="muted">Contacts</span><div className="metric">{a.contacts.length}</div></div></div>
{brief&&<section className="card section brief-card"><div className="row-between"><div><div className="eyebrow">Account brief · Version {brief.version}</div><h2>AI-assisted account intelligence</h2></div><span className={`status status-${brief.reviewStatus==='accepted'?'complete':'active'}`}>{brief.reviewStatus}</span></div><p className="brief-summary">{brief.summary}</p><div className="grid three-col"><div><h3>Opportunities</h3><ul>{brief.opportunities.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Risks</h3><ul>{brief.risks.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Recommended actions</h3><ol>{brief.recommendedActions.map(x=><li key={x}>{x}</li>)}</ol></div></div><small className="muted">Confidence {brief.confidence}% · {brief.sourceCount} sources · Generated {new Date(brief.generatedAt).toLocaleString()}</small></section>}<div className="grid two-col section"><section className="card"><h2>Account overview</h2><dl className="detail-list"><div><dt>Owner</dt><dd>{a.owner}</dd></div><div><dt>Website</dt><dd>{a.website??'Not available'}</dd></div><div><dt>Phone</dt><dd>{a.phone??'Not available'}</dd></div><div><dt>Last activity</dt><dd>{a.lastActivity??'None'}</dd></div><div><dt>Next action</dt><dd>{a.nextAction??'Not set'}</dd></div></dl><div className="tag-row">{a.tags.map(t=><span className="pill" key={t}>{t}</span>)}</div></section><section className="card"><h2>Source lineage</h2>{a.sourceLinks.length?a.sourceLinks.map(s=><div className="source-card" key={s.externalId}><strong>{s.system}</strong><code>{s.externalId}</code><small>Last synchronized {new Date(s.lastSynced).toLocaleString()}</small></div>):<p className="muted">No external source links.</p>}</section></div>
<section className="section"><div className="row-between"><h2>Properties</h2><button className="secondary-btn">Add property</button></div><table className="table"><thead><tr><th>Property</th><th>Type</th><th>Address</th><th>Relationship</th><th>Source</th></tr></thead><tbody>{a.properties.length?a.properties.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.type.replaceAll('_',' ')}</td><td>{p.address}, {p.city}, {p.state} {p.postalCode}</td><td>{p.relationship.replaceAll('_',' ')}</td><td>{p.sourceSystem??'Manual'}<small className="table-sub">{p.externalId}</small></td></tr>):<tr><td colSpan={5}>No linked properties.</td></tr>}</tbody></table></section>
<section className="section"><div className="row-between"><h2>Contacts</h2><button className="secondary-btn">Add contact</button></div><table className="table"><thead><tr><th>Contact</th><th>Title</th><th>Decision role</th><th>Contact information</th><th>Verification</th></tr></thead><tbody>{a.contacts.length?a.contacts.map(c=><tr key={c.id}><td><strong>{c.firstName} {c.lastName}</strong></td><td>{c.title}<small className="table-sub">{c.department}</small></td><td>{c.decisionRole.replaceAll('_',' ')}</td><td>{c.email??'—'}<small className="table-sub">{c.phone}</small></td><td><span className={`status status-${c.verification==='verified'?'complete':'not_started'}`}>{c.verification}</span></td></tr>):<tr><td colSpan={5}>No linked contacts.</td></tr>}</tbody></table></section>
<section className="card section"><h2>Activity timeline</h2><div className="timeline">{a.activities.map(x=><div className="timeline-item" key={x.id}><span className="timeline-dot"/><div><strong>{x.summary}</strong><p className="muted">{x.actor} · {new Date(x.occurredAt).toLocaleString()}</p></div></div>)}</div></section>
</>}
