create schema if not exists rollout;
create table if not exists rollout.cohorts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),name text not null,status text not null check(status in('planned','onboarding','live','stabilizing','graduated','paused')),owner_user_id uuid,planned_users int not null default 0,certified_users int not null default 0,planned_accounts int not null default 0,target_live_at timestamptz,graduated_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists rollout.migration_controls(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),cohort_id uuid references rollout.cohorts(id),dataset_name text not null,source_count bigint not null default 0,target_count bigint not null default 0,exception_count bigint not null default 0,status text not null check(status in('not_started','running','reconciled','failed')),blocking boolean not null default true,source_snapshot jsonb not null default '{}'::jsonb,target_snapshot jsonb not null default '{}'::jsonb,reconciled_at timestamptz,created_at timestamptz not null default now());
create table if not exists rollout.training_certifications(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),cohort_id uuid references rollout.cohorts(id),user_id uuid not null,module_key text not null,status text not null check(status in('assigned','in_progress','passed','failed','waived')),score numeric(5,2),passing_score numeric(5,2),evidence jsonb not null default '{}'::jsonb,certified_at timestamptz,unique(workspace_id,cohort_id,user_id,module_key));
create table if not exists rollout.adoption_measurements(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),cohort_id uuid references rollout.cohorts(id),metric_key text not null,measured_at timestamptz not null,value numeric not null,target numeric,direction text check(direction in('higher','lower')),source_snapshot jsonb not null default '{}'::jsonb);
create table if not exists rollout.hypercare_issues(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),cohort_id uuid references rollout.cohorts(id),title text not null,severity text not null check(severity in('critical','high','medium','low')),status text not null check(status in('open','investigating','mitigated','resolved')),owner_user_id uuid,opened_at timestamptz not null default now(),resolved_at timestamptz,root_cause text,remediation text,audit_correlation_id uuid);
create table if not exists rollout.stabilization_gates(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id),cohort_id uuid references rollout.cohorts(id),name text not null,status text not null check(status in('pass','warning','fail')),blocking boolean not null default true,evidence jsonb not null default '{}'::jsonb,approved_by uuid,approved_at timestamptz);
alter table rollout.cohorts enable row level security;alter table rollout.migration_controls enable row level security;alter table rollout.training_certifications enable row level security;alter table rollout.adoption_measurements enable row level security;alter table rollout.hypercare_issues enable row level security;alter table rollout.stabilization_gates enable row level security;
create policy cohorts_workspace on rollout.cohorts using(platform.is_workspace_member(workspace_id));create policy migration_workspace on rollout.migration_controls using(platform.is_workspace_member(workspace_id));create policy training_workspace on rollout.training_certifications using(platform.is_workspace_member(workspace_id));create policy adoption_workspace on rollout.adoption_measurements using(platform.is_workspace_member(workspace_id));create policy hypercare_workspace on rollout.hypercare_issues using(platform.is_workspace_member(workspace_id));create policy gates_workspace on rollout.stabilization_gates using(platform.is_workspace_member(workspace_id));
