create schema if not exists security;
create table if not exists security.controls(id uuid primary key default gen_random_uuid(),workspace_id uuid references platform.workspaces(id),framework text not null,control_code text not null,title text not null,owner_user_id uuid,status text not null check(status in('effective','partial','ineffective','not_tested')),last_tested_at timestamptz,next_test_at timestamptz not null,created_at timestamptz not null default now(),unique(workspace_id,framework,control_code));
create table if not exists security.control_evidence(id uuid primary key default gen_random_uuid(),control_id uuid not null references security.controls(id) on delete cascade,evidence_type text not null,object_reference text not null,checksum text,period_start timestamptz,period_end timestamptz,collected_at timestamptz not null default now(),collected_by uuid);
create table if not exists security.findings(id uuid primary key default gen_random_uuid(),workspace_id uuid references platform.workspaces(id),finding_number text not null unique,title text not null,severity text not null check(severity in('critical','high','medium','low')),status text not null check(status in('open','mitigating','accepted','resolved')),asset_reference text not null,owner_user_id uuid,discovered_at timestamptz not null,due_at timestamptz not null,exploit_available boolean not null default false,internet_exposed boolean not null default false,accepted_by uuid,accepted_until timestamptz,resolved_at timestamptz,created_at timestamptz not null default now());
create table if not exists security.data_assets(id uuid primary key default gen_random_uuid(),workspace_id uuid references platform.workspaces(id),name text not null,system_name text not null,classification text not null check(classification in('public','internal','confidential','restricted')),owner_user_id uuid,contains_personal_data boolean not null default false,retention_days int not null check(retention_days>=0),encrypted_at_rest boolean not null,encrypted_in_transit boolean not null,created_at timestamptz not null default now());
create table if not exists security.privacy_requests(id uuid primary key default gen_random_uuid(),workspace_id uuid references platform.workspaces(id),request_number text not null unique,request_type text not null check(request_type in('access','deletion','correction','portability','opt_out')),status text not null check(status in('received','verified','in_progress','completed','denied')),jurisdiction text not null,received_at timestamptz not null,due_at timestamptz not null,verified_at timestamptz,completed_at timestamptz,owner_user_id uuid,identity_evidence_reference text,created_at timestamptz not null default now());
create table if not exists security.events(id uuid primary key default gen_random_uuid(),workspace_id uuid references platform.workspaces(id),category text not null,severity text not null,occurred_at timestamptz not null,source text not null,disposition text not null,summary text not null,correlation_id text,created_at timestamptz not null default now());
alter table security.controls enable row level security;alter table security.findings enable row level security;alter table security.data_assets enable row level security;alter table security.privacy_requests enable row level security;alter table security.events enable row level security;
create policy controls_workspace_access on security.controls for all using(workspace_id is null or platform.is_workspace_member(workspace_id));create policy findings_workspace_access on security.findings for all using(workspace_id is null or platform.is_workspace_member(workspace_id));create policy data_assets_workspace_access on security.data_assets for all using(workspace_id is null or platform.is_workspace_member(workspace_id));create policy privacy_requests_workspace_access on security.privacy_requests for all using(workspace_id is null or platform.is_workspace_member(workspace_id));create policy security_events_workspace_access on security.events for all using(workspace_id is null or platform.is_workspace_member(workspace_id));
