-- Step 38: Production deployment, observability, and operational readiness
create table if not exists public.production_deployments (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,version text not null,environment text not null,status text not null check(status in('planned','running','succeeded','failed','rolled_back')),started_at timestamptz not null,completed_at timestamptz,strategy text not null check(strategy in('rolling','blue_green','canary')),rollback_available boolean not null default false,change_owner text not null,created_at timestamptz not null default now());
create table if not exists public.telemetry_signals (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,service text not null,signal text not null check(signal in('logs','metrics','traces','synthetics')),coverage_pct numeric(5,2) not null check(coverage_pct between 0 and 100),retention_days integer not null check(retention_days>=0),last_ingest_at timestamptz,status text not null check(status in('healthy','degraded','missing')),unique(workspace_id,service,signal));
create table if not exists public.operational_runbooks (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,name text not null,service text not null,owner text not null,status text not null check(status in('draft','approved','stale')),last_reviewed_at date not null,review_due_at date not null,automated_steps integer not null default 0,manual_steps integer not null default 0);
create table if not exists public.operational_alerts (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,title text not null,service text not null,severity text not null check(severity in('critical','high','medium','low')),status text not null check(status in('open','acknowledged','resolved','suppressed')),owner text not null,opened_at timestamptz not null,acknowledged_at timestamptz,resolved_at timestamptz,runbook_id uuid references public.operational_runbooks(id) on delete set null);
create table if not exists public.on_call_rotations (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,team text not null,primary_contact text not null,secondary_contact text not null,timezone text not null,coverage_hours integer not null check(coverage_hours between 0 and 24),handoff_at time not null,escalation_policy text not null);
create table if not exists public.go_live_controls (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references platform.workspaces(id) on delete cascade,name text not null,owner text not null,required boolean not null default true,status text not null check(status in('ready','at_risk','blocked')),evidence text not null default '');
create index if not exists production_deployments_workspace_idx on public.production_deployments(workspace_id,environment,started_at desc);create index if not exists operational_alerts_workspace_idx on public.operational_alerts(workspace_id,severity,status);create index if not exists go_live_controls_workspace_idx on public.go_live_controls(workspace_id,status);
alter table public.production_deployments enable row level security;alter table public.telemetry_signals enable row level security;alter table public.operational_alerts enable row level security;alter table public.operational_runbooks enable row level security;alter table public.on_call_rotations enable row level security;alter table public.go_live_controls enable row level security;
create policy "workspace members manage production deployments" on public.production_deployments using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));create policy "workspace members manage telemetry signals" on public.telemetry_signals using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));create policy "workspace members manage operational alerts" on public.operational_alerts using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));create policy "workspace members manage operational runbooks" on public.operational_runbooks using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));create policy "workspace members manage on call rotations" on public.on_call_rotations using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));create policy "workspace members manage go live controls" on public.go_live_controls using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
