import Link from 'next/link';
import { getWorkspaceContext } from '@/lib/workspace-context';
import { getOrganizations } from '@/lib/data/entities';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default async function Page(){const {activeWorkspace}=await getWorkspaceContext();const rows=await getOrganizations(activeWorkspace!.id);return <>
<div className="hero"><div><h1>Account Intelligence</h1><p className="muted">Global organizations with workspace-specific ownership, status, source lineage, and opportunity context.</p></div><Link className="btn" href="/accounts/new">Add organization</Link></div>
<div className="grid cards section"><div className="card"><span className="muted">Accounts</span><div className="metric">{rows.length}</div></div><div className="card"><span className="muted">A-priority</span><div className="metric">{rows.filter(x=>x.priority==='A').length}</div></div><div className="card"><span className="muted">Property relationships</span><div className="metric">{rows.reduce((n,x)=>n+x.propertyCount,0)}</div></div><div className="card"><span className="muted">Identified pipeline</span><div className="metric">{money.format(rows.reduce((n,x)=>n+x.opportunityValue,0))}</div></div></div>
<div className="filterbar section"><input className="input compact" placeholder="Search accounts, cities, industries…"/><select className="input compact"><option>All lifecycle statuses</option><option>Customer</option><option>Prospect</option></select><select className="input compact"><option>All priorities</option><option>A</option><option>B</option><option>C</option></select></div>
<div className="table-scroll"><table className="table"><thead><tr><th>Account</th><th>Lifecycle</th><th>Priority</th><th>Score</th><th>Relationships</th><th>Owner</th><th>Next action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link className="text-link" href={`/accounts/${r.id}`}>{r.name}</Link><small className="table-sub">{r.industry} · {r.city}, {r.state}</small></td><td><span className="pill">{r.lifecycle}</span></td><td><strong>{r.priority}</strong></td><td><strong>{r.score}</strong><small className="table-sub">{r.dataConfidence}% confidence</small></td><td>{r.propertyCount} properties<br/><small>{r.contactCount} contacts</small></td><td>{r.owner}</td><td>{r.nextAction??'Not set'}</td></tr>)}</tbody></table></div>
</>}
